version: '3.7'
services:
  gateway: 
    image: nginx:1.22.0-alpine
    container_name: gateway
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
    ports:
      - 80:80
    depends_on:
      - app
    restart: always
  
  app:
    image: node:18.3.0-alpine
    container_name: app
    working_dir: /app
    volumes:
      - ./app:/app
      - type: bind
        source: ./app.sh
        target: /entrypoint.sh
    networks:
      - app-network
    ports:
      - 3000:3000
    restart: always
    command: sh /entrypoint.sh

networks: 
  app-network:
    driver: bridge